"""artifact concepts <>

Revision ID: 2e1dd58906a9
Revises: 
Create Date: 2021-01-08 14:54:19.464632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1dd58906a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artifacts_concept_id_fkey', 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'concept_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artifacts_concept_id_fkey', 'artifacts', 'concepts', ['concept_id'], ['id'])
    # ### end Alembic commands ###
