"""artifact prerequires concepts, not self

Revision ID: 3f3a0c542721
Revises: f151e41d94e2
Create Date: 2021-01-08 16:09:04.713169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3a0c542721'
down_revision = 'f151e41d94e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column('artifacts', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('artifacts', 'name')
    op.drop_column('artifacts', 'introduction')
    op.add_column('prerequisites', sa.Column('artifact_id', sa.Integer(), nullable=True))
    op.add_column('prerequisites', sa.Column('concept_id', sa.Integer(), nullable=True))
    op.drop_constraint('prerequisites_after_id_fkey', 'prerequisites', type_='foreignkey')
    op.drop_constraint('prerequisites_before_id_fkey', 'prerequisites', type_='foreignkey')
    op.create_foreign_key(None, 'prerequisites', 'concepts', ['concept_id'], ['id'])
    op.create_foreign_key(None, 'prerequisites', 'artifacts', ['artifact_id'], ['id'])
    op.drop_column('prerequisites', 'after_id')
    op.drop_column('prerequisites', 'before_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prerequisites', sa.Column('before_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('prerequisites', sa.Column('after_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prerequisites', type_='foreignkey')
    op.drop_constraint(None, 'prerequisites', type_='foreignkey')
    op.create_foreign_key('prerequisites_before_id_fkey', 'prerequisites', 'artifacts', ['before_id'], ['id'])
    op.create_foreign_key('prerequisites_after_id_fkey', 'prerequisites', 'artifacts', ['after_id'], ['id'])
    op.drop_column('prerequisites', 'concept_id')
    op.drop_column('prerequisites', 'artifact_id')
    op.add_column('artifacts', sa.Column('introduction', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('artifacts', 'title')
    op.drop_column('artifacts', 'description')
    # ### end Alembic commands ###
