"""artifact has one concept

Revision ID: 430d45c8d5a8
Revises: 359c12f32463
Create Date: 2021-01-11 16:59:50.909503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430d45c8d5a8'
down_revision = '359c12f32463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_artifacts')
    op.add_column('artifacts', sa.Column('concept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artifacts', 'concepts', ['concept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'concept_id')
    op.create_table('concept_artifacts',
    sa.Column('artifact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name='concept_artifacts_artifact_id_fkey'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='concept_artifacts_concept_id_fkey')
    )
    # ### end Alembic commands ###
