"""delete old concept artifacts table

Revision ID: 710a2f4b5129
Revises: 102233e11f67
Create Date: 2021-01-26 16:42:06.074466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710a2f4b5129'
down_revision = '102233e11f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('topics')
    op.drop_table('prerequisites')
    op.drop_table('concept_resources')
    op.drop_table('nested_concepts')
    op.drop_table('studyplans')
    op.drop_table('resources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('resources_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('est_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vote_sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='resources_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resources_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('studyplans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('studyplans_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='studyplans_concept_id_fkey'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='studyplans_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='studyplans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('nested_concepts',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['concepts.id'], name='nested_concepts_child_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['concepts.id'], name='nested_concepts_parent_id_fkey')
    )
    op.create_table('concept_resources',
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='concept_resources_concept_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='concept_resources_resource_id_fkey')
    )
    op.create_table('prerequisites',
    sa.Column('artifact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name='prerequisites_artifact_id_fkey'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='prerequisites_concept_id_fkey')
    )
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topics_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('studyplan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='topics_concept_id_fkey'),
    sa.ForeignKeyConstraint(['studyplan_id'], ['studyplans.id'], name='topics_studyplan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='topics_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='readings_resource_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='readings_topic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='readings_pkey')
    )
    # ### end Alembic commands ###
