"""add artifact specific prereqs

Revision ID: 7ee14e690b7a
Revises: 710a2f4b5129
Create Date: 2021-01-29 16:52:07.098533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee14e690b7a'
down_revision = '710a2f4b5129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prerequisites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prerequisites',
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artifact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name='prerequisites_artifact_id_fkey'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='prerequisites_concept_id_fkey')
    )
    # ### end Alembic commands ###
