"""artifact chunks one to many

Revision ID: f151e41d94e2
Revises: 2e1dd58906a9
Create Date: 2021-01-08 15:24:15.036857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f151e41d94e2'
down_revision = '2e1dd58906a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'title')
    # ### end Alembic commands ###
